### ISSUE TITLE
acme-v2

### ISSUE THREAD

**Issue by Nyantechnolog** [jonremy/rancher-auto-certs#1]
Hi, acme-v1 is not working anymore, so you need to update it.  It's enough to update acme-tiny.py to 4.0.4 version (or most recent). In latest version change chain so I take 4.0.4. 
And also change ca in config.yml to https://acme-v02.api.letsencrypt.org (it's deprecated but, so maybe you want to change to https://acme-v02.api.letsencrypt.org/directory.

i tried and it's work fine. 
Thank for u soft. It really helps my team. Good luck.

**Comment by jonremy** [comment]
Hi, thanks for your interest in this tool!
I just updated it to use acme-tiny v4.1.0 and so ACME v2. There is a new `ca_directory` key in the config (`ca` should still be supported though), and the chain cert url is not not necessary anymore as with ACME v2 the chain part [is included with the certificate](https://github.com/diafygi/acme-tiny/commit/7a4ea10d08b8a01b625f5df4c9ca173c9318bfe0)
